### ISSUE TITLE
Incubation status?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/lock-screen#7]
Hi, just checking the status of this incubation as there appears to have been little activity in the last few years. 

Is this something that is still being actively perused? If not, is it ok if the @WICG/chairs archive this repo?

**Comment by phoglenix** [comment]
Per https://lists.w3.org/Archives/Public/public-wicg/2023Feb/0016.html we are no longer pursuing this API and it can be archived.

**Comment by yoavweiss** [comment]
Thanks! Archiving..
